services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${BASE_DOMAIN}`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.entrypoints=http,https
      - traefik.http.routers.radarr.tls.certresolver=letsencrypt
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.middlewares=auth@file
      - external=true
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Vancouver
      - UMASK=000
    volumes:
      - /mnt/user/appdata/binhex-radarr:/config
      - /mnt/user/data:/data
    networks:
      - jarvis

networks:
  jarvis:
    external: true