services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.${BASE_DOMAIN}`)
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.entrypoints=http,https
      - traefik.http.routers.adminer.tls.certresolver=letsencrypt
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer.middlewares=auth@file
      - external=true
    environment:
      - TZ=America/Vancouver
      - ADMINER_DESIGN=flat
      - ADMINER_PLUGINS=
    networks:
      - jarvis

networks:
  jarvis:
    external: true