services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.crafty.rule=Host(`crafty.${BASE_DOMAIN}`)
      - traefik.http.routers.crafty.tls=true
      - traefik.http.routers.crafty.entrypoints=http,https
      - traefik.http.routers.crafty.tls.certresolver=letsencrypt
      - traefik.http.services.crafty.loadbalancer.server.port=8443
      - traefik.http.services.crafty.loadbalancer.server.scheme=https
      # Optional: Add Authelia protection (uncomment if desired)
      # - traefik.http.routers.crafty.middlewares=auth@file
      - external=true
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Vancouver
    volumes:
      - /mnt/user/appdata/crafty/backups:/crafty/backups
      - /mnt/user/appdata/crafty/logs:/crafty/logs
      - /mnt/user/appdata/crafty/servers:/crafty/servers
      - /mnt/user/appdata/crafty/config:/crafty/app/config
      - /mnt/user/appdata/crafty/import:/crafty/import
    ports:
      # Minecraft server ports - official recommended range
      - "25500-25600:25500-25600"  # Minecraft server port range
      - "8123:8123"                # Dynmap (optional)
      - "19132:19132/udp"          # Bedrock server port
      # Port 8443 removed - accessed via Traefik only
    networks:
      - jarvis
# Test auto-deploy2 - 2024-10-27
networks:
  jarvis:
    external: true