
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Vancouver
      - TS_AUTHKEY=${TS_AUTHKEY}  # Replace with your actual auth key
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-routes=192.168.10.0/24 --accept-routes --advertise-tags=tag:server
    volumes:
      - /mnt/user/appdata/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true